name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # use a versão que está no seu projeto
          channel: stable
          cache: true

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-pub

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release
